version: "3.9"
services:
  sharewise-client:
    image: nginx:alpine
    volumes:
      - ./Client:/usr/share/nginx/html
    ports:
      - "80:80"

  sharewise-api:
    image: shaunmadziva/sharewise-api:new
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - sharewise-db
    networks:
      - sharewise-network

  sharewise-db:
    image: shaunmadziva/sharewise-db:new
    ports:
      - "5432:5432"
    restart: always

    networks:
      - sharewise-network

networks:
  sharewise-network:
