version: "3.9"
services:
  sharewise-api:
    image: shaunmadziva/project-sharewise-api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - sharewise-db
    networks:
      - sharewise-network

  sharewise-db:
    image: shaunmadziva/project-sharewise-db
    ports:
      - "5432:5432"
    restart: always

    networks:
      - sharewise-network

networks:
  sharewise-network:
