version: "3.9"
services:
  sharewise-client:
    image: nginx:alpine
    volumes:
      - ./Client:/usr/share/nginx/html
    ports:
      - "80:80"

  sharewise-api:
    build:
      context: ./sharewise-api  # ✅ Set build context to where Dockerfile + index.js live
      dockerfile: Dockerfile 
    image: shaunmadziva/project-sharewise-api
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - sharewise-db
    networks:
      - sharewise-network

  sharewise-db:
    build:
      context: ./sharewise-db  # ✅ Set build context to where Dockerfile + index.js live
      dockerfile: Dockerfile 
    image: shaunmadziva/project-sharewise-db
    ports:
      - "5432:5432"
    restart: always

    networks:
      - sharewise-network

networks:
  sharewise-network:
