- hosts: all
  become: true
  tasks:
    - name: Create new directory
      ansible.builtin.file:
        path: /home/ec2-user/project-sharewise
        owner: ec2-user
        group: ec2-user
        state: directory
      
    - name: Install git
      yum:
        name: git
        state: present
      become: true

    - name: Clone a github repository
      git:
        repo: https://github.com/ShaunMadziva/project-sharewise.git
        dest: /home/ec2-user/project-sharewise
        clone: yes
        update: yes

    - name: Ensure docker-compose.yml exists and is not empty
      stat:
        path: /home/ec2-user/project-sharewise/docker-compose.yml
      register: compose_file

    - name: Fail if docker-compose.yml is missing or empty
      fail:
        msg: "docker-compose.yml is missing or empty"
      when: not compose_file.stat.exists or compose_file.stat.size == 0
      
    - name: Run docker-compose
      shell: docker-compose up -d
      args:
        chdir: /home/ec2-user/project-sharewise

