pipeline {
    agent any

    environment {
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key-id')
    }

    stages {
        stage('Terraform init') {
            steps {
                script {

                    sh '''
                        #!/bin/bash
                        cd infrastructure
                        echo "Initializing terraform"
                        terraform init
                       
                    '''
                }
            }
        }

        stage ('Terraform apply') {
            steps {
                script {
                    sh '''
                        #!/bin/bash
                        cd infrastructure
                        echo "Provisioning infrastructure"
                        terraform apply -auto-approve
                    '''
                }
            }
        }
    }
}