pipeline {
  agent any

  environment {
    ANSIBLE_HOST_KEY_CHECKING = 'False'
  }

  stages {
    stage('Install Requirements') {
      steps {
        sh 'sudo apt-get update'
        sh 'sudo apt-get install -y ansible ssh'
      }
    }

    stage('Run Ansible Playbook') {
      steps {
        sh '''
        ansible-playbook -i inventory_hosts ansible/playbook.yml --private-key $PRIVATE_KEY_FILE
        '''
      }
    }
  }
}